export const settingConstants = {
  ADMIN_PROFILE: 'Admin Profile',
  EDIT_PROFILE: 'Edit Profile',
  NAME: 'Name',
  EMIAL: 'Email',
  OFFICE_PHONE_NUMBER: 'Office Phone Number',
  USER_TYPE: 'User Type',
  ROLE_TYPE: 'Role Type',
  ROLE: 'Role',
  CHANGE_PASSWORD: 'Change Password',
  EDIT_ADMIN_PROFILE: 'Edit Admin Profile',
  PROFILE_PROTO: 'Profile Photo',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL: 'Email',
  CONTACT_NUMBER: 'Contact Number',
  ENTER: 'Enter',
  SAVE: 'Save',
  CURRENT_PASSWORD: 'Current Password',
  NEW_PASSWORD: 'New Password',
  CONFIRM_NEW_PASSWORD: 'Confirm New Password',
  UPDATE_PASSWORD: 'Update Password',
  USERS: 'Users',
  RESET: 'Reset',
  ADMIN_NAME: 'Admin Name',
  STATUS: 'Status',
  ADD_USER: 'Add User',
  SEARCH_USER: 'Search User',
  NPI_NUMBER: 'NPI Number',
  GENDER: 'Gender',
  CLINICS: 'Clinics',
  CANCEL: 'Cancel',
  SELECT: 'Select',
  ACTIVE_STATUS: 'Active Status',
  ICD_CODE_NAME: 'Add ICD-10 Code',
  ICD_DESCRIPTION: 'Add Description',
  DESCRIPTION: 'Description',
  SUBMIT: 'Submit',
  CPT_CODE_NAME: 'Add Code',
  CPT_DESCRIPTION: 'Add Description',
  CPT_CODE: 'Code',
  ADMIN_MASTER_TAB_SEARCH_PLACEHOLDER: 'Search by ICD-10 Code',
  ADMIN_MASTER_TAB_SEARCH_PLACEHOLDERS_CPT: 'Search by Procedure Code',
  AN_ERROR: 'An Error Occured',
  DOCUMENT_UPLOAD: 'Document Uploaded Successfully',
  SELECT_TYPE: 'Select Type',
  TYPE: 'Type',
  PROVIDER_GROUP_NAME: 'Provider Group Name',
  ENTER_PROVIDER_GROUP_NAME: 'Enter provider Group Name',
  SELECT_PROVIDER_GROUP_NAME: 'Select Provider Group Name',
  BACK: 'Back',
  STEPCS_COMPLETED: "All steps completed - you're finished",
  UPLOAD: 'Upload',
  UPLOAD_DATA: 'Upload Data',
  UPLOAD_IMPORT: 'Upload Import',
  LAST_STEP: 'Last step',
  DOWNLOAD_CSV: 'Download Blank CSV Template',
  FAMILY_TEXT: 'Family Psychotherapy without patient present',
  CONFIRM_POP: 'Do you really want to change this status ?',
  SELECT_PROVIDER_TYPE: 'Select Clinician Type',
  SPECIALITY: 'Speciality',
  SELECT_SPECIALITY: 'Select Speciality',
  SELECT_ROLE: 'Select Role',
  SELECT_GENDER: 'Select Gender',
  LICENSE_STATES: 'State(s)',
  SELECT_LICENSE_STATES: 'Select State(s)',
  WORK_LOCATION: 'Work Locations',
  SELECT_WORK_LOCATION: 'Select Work Locations',
  SPECIALITY_TYPE: 'Speciality',
  SELECT_SPECIALITY_TYPE: 'Select Speciality',
  EDIT_PROVIDER: 'Edit Clinician User',
  EDIT_STAFF: 'Edit Staff User',
  SEARCH_BY_LOC_NAME: 'Search by Location Name',
  LOCATION_NAME: 'Location Name',
  LOCATION_ID: 'Location ID',
  BILLING_ADDRESS: 'Billing Address',
  PHYSICAL_ADDRESS: 'Physical Address',
  SPECIALITIES: 'Specialities',
  FAX_ID: 'Fax ID',
  INFORMATION: 'Information',
  LOCATION_HOURS: 'Location Hours',
  SEARCH_BY_USER_NAME: 'Search by User Name',
  EDIT_USER: 'Edit User',
  PROVIDER_TYPE: 'Clinician Type',
  BIO: 'Bio',
  INS_VERIFICATION: 'Insurance Verification',
  ENTER_INS_VERIFICATION: 'Enter Insurance Verification',
  OFF_FAX_NUM: 'Office Fax Number',
  SPECIALTIES: 'Specialties',
  WORK_EXP: 'Work Experience',
  YR_OF_EXP: 'Work Experience',
  ENTER_YR_OF_EXP: 'Enter Work Experience',
  ADDRESS_LINE_1: 'Line 1',
  ADDRESS_LINE_2: 'Line 2',
  STATE: 'State',
  CITY: 'City',
  ZIP_CODE: 'Zip Code',
  VIEW_USER_DETAILS: 'View User Details',
  BASIC_INFORMATION: 'Basic Information',
  DOCUMENT_TYPES: 'Document Types',
  ADD_DOCUMENT_TYPE: 'Add Document Type',
  EDIT_DOCUMENT_TYPE: 'Edit Document Type',
  DOCUMENT_TYPE: 'Document Type',
  ENTER_DOCUMENT_TYPE: 'Enter Document Type',
  LANGUAGE: 'Language',
  AREA_OF_FCS: 'Sub-Specialties / Areas of Focus',
  LICENSE_NUMBER: 'License Number',
  LICENSE_EXPIRY_DATE: 'License Expiry Date',
  LICENSE_STATE: 'License State',
  ENTER_LICENSE_NUMBER: 'Enter Number',
  ENTER_LICENSE_EXPIRY_DATE: 'Enter Expiry Date',
  PRACTICE: 'Practice',
  TEMPLATE_NAME: 'Template Name',
  TEMPLATE_TYPE: 'Template Type',
  TEMPLATE_DATA: 'Template Data',
  PATIENT_FLAG: 'Patient Flag',
  ADD_PATIENT_FLAG: 'Add Patient Flag',
  SEARCH_FLAG_NAME: 'Search Flag Name',
  EDIT_PATIENT_FLAG: 'Edit Patient Flag',
  LICENSED_DETAILS: 'Licensed Details',
  CONTACT: 'Contact',
  NO_CLINICS_FOUND: 'No Clinics Found',
};

export const clinicConstants = {
  MEDICAL_CODES: 'Medical Codes',
  BASIC_INFORMATION: 'Basic Information',
  ADD_CLINIC_IMAGE: 'Add Clinic Logo',
  CLINIC: 'Clinic',
  CLINICS: 'Clinics',
  ACTIVE_CLINICS: 'Active Clinics',
  PROVIDERS: 'Active Clinician',
  PATIENTS: 'Active Patients',
  SEARCH_HERE: 'Search Clinic name',
  CLINIC_NAME: 'Clinic Name',
  STATUS: 'Status',
  SEARCH_AND_SELECT_STATE: 'Search & Select State',
  ADD_CLINIC: 'Add Clinic',
  ADD_NEW_CLINIC: 'Add New Clinic',
  ENTER: 'Enter',
  TIMEZONE: 'Timezone',
  CONTACT_NUMBER: 'Contact Number',
  SELECT: 'Select',
  ACTIVE_STATUS: 'Active Status',
  SPECIALITY_TYPE: 'Speciality Type',
  GROUP_NPI_NUMBER: 'Group NPI Number',
  EMAIL: 'Email',
  WEBSITE: 'Website',
  FAX_ID: 'Fax ID',
  INFORMATION: 'Information',
  ADDRESS: 'Address',
  PHYSICAL_ADDRESS: 'Physical Address',
  BILLING_ADDRESS: 'Billing Address',
  LINE_1: 'Line 1',
  LINE_2: 'Line 2',
  CITY: 'City',
  STATE: 'State',
  COUNTRY: 'Country',
  ZIP_CODE: 'Zip Code',
  CLINIC_OFFICE_HOURS: 'Clinic Office Hours',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  EDIT_CLINIC: 'Edit Clinic',
};

export const locationConstants = {
  LOCATION_NAME: 'Location Name',
  LOCATION_ID: 'Location ID',
  SPECIALITY: 'Speciality',
  CONTACT_NUMBER: 'Contact Number',
  GROUP_NPI_NUMBER: 'Group NPI Number',
  TIMEZONE: 'Timezone',
  EMAIL: 'Email',
  FAX_ID: 'Fax ID',
  INFORMATION: 'Information',
  PHYSICAL_ADDRESS: 'Physical Address',
  BILLING_ADDRESS: 'Billing Address',
  LINE_1: 'Line 1',
  LINE_2: 'Line 2',
  CITY: 'City',
  STATE: 'State',
  COUNTRY: 'Country',
  ZIP_CODE: 'Zip Code',
  LOCATION_HOURS: 'Location Hours',
  ACTIVE: 'Active',
  ARCHIVE: 'Archive',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  ADD_LOCATION: 'Add Location',
  EDIT_LOCATION: 'Edit Location',
  ADD_NEW_LOCATION: 'Add New Location',
  ENTER: 'Enter',
  ADD_LOCATION_HOURS: 'Add Location Hours',
  DAY_OF_WEEK: 'Day of Week',
  OPENING_TIME: 'Opening Time',
  CLOSING_TIME: 'Closing Time',
  OFFICE_HOURS: 'Office Hours',
};
