export const dashboardConstants = {
  DASHBOARD: 'Dashboard',
  UNCHECK_NOTIFICATION: 'Uncheck Notification',
  CALENDER_RANGE: 'Calender range',
  VIEW_REPORT: 'View Report',
  APPOINTMENTS: 'Appointments',
  SCHEDULING: 'Scheduling',
  MESSAGES: 'Messages',
  UPCOMMING_APPOINTMENTS: 'Upcomming Appointments',
  TO_DO_TASK: 'To Do Task',
  REQUEST: 'Requests',
};

export const intakeFormConstants = {
  PATIENT_INTAKE_FORM: 'Patient Intake Form',
  PENDING_REVIEW: 'Pending Review',
  NOT_SUBMITTED_BY_PATIENT: 'Not Submitted By Patient',
  SEND_FORM: 'Send Form',
  SEND_FORM_TO_PATIENT: 'Send Form To Patient',
  PROVIDER: 'Provider',
  SEARCH_PROVIDER: 'Search provider',
  PATIENT_NAME: 'Patient Name',
  SEARCH_PATIENT: 'Search Patient',
  PATIENT_INTAKE: 'Patient Intake',
  SEARCH_AND_SELECT_FORM: 'Search & Select Form',
  EMAIL_TO: 'Email to ',
  SEND_SMS_TO: 'Send SMS to',
  SEND: 'Send',
};

export const ePrescriptionConstants = {
  GO_TO_PATIENT_CHART: 'Go To Patient Chart',
  EPRESCRIPTION_REQUEST: 'E-Prescription Request',
  RENEWAL_REQUESTS: 'Renewal Requests',
  CHANGE_REQUESTS: 'Change Requests',
  CANCEL_REQUESTS: 'Cancel Requests',
  FILL_RESPONSES: 'Fill Response',
  SEND_FAILURES: 'Send Failures',
};

export const labRequestConstants = {
  LAB_REQUEST: 'Lab Results',
  RESULT_AVAILABLE: 'Result Available',
  PENDING: 'Pending',
  RECENTLY_SIGNED: 'recently Signed',
  UNMATCHED: 'Unmatched',
  CREATE_ORDER: 'Create Order',
  LAB_REQUISTION_FORM: 'Lab Requisition Form',
  LOCATION: 'Location',
  SEARCH_AND_SELECT_LOCATION: 'Search and Select Location',
  LAB: 'Lab',
  SEARCH_AND_SELECT: 'Search and Select',
  BILL_TYPE: 'Bill Type',
  PATIENT: 'Patient',
  PROVIDER: 'Provider',
  INSURANCE: 'Insurance',
  TEST: 'Test',
  SEARCH_AND_SELECT_TEST: 'Search and Select Test',
  SAVE_AS_ORDER_SET: 'Save as Order Set',
  ICD_CODE: 'ICD Code',
  SEARCH_AND_SELECT_ICD: 'Search and Select ICD',
  PATIENT_INSTRUCTIONS: 'Patient Instructions',
  LAB_INSTRUCTIONS_TO_TEST_CENTER: 'Lab Instructions To Test Center',
  COLLECTION_DATE_AND_TIME: 'Collection Date & Time',
  DATE: 'Date',
  TIME: 'Time',
  NOTE: 'Note',
  NOTE_DESC:
    'If result are not received within this time period, we’ll send you a reminder to follow up with the patient',
  CHART_NOTE: 'Chart Note',
  SELECT_A_CHART_NOTE: 'Select a Chart Note',
  PRINT_AND_CLOSE: 'Print & Close',
  ORDER: 'Order',
};

export const dialogConstant = {
  MRN: 'MRN',
  PHARMACY_INFORMATION: 'Pharmacy Information',
  RENEWAL_REQUESTS: 'Renewal Request',
  CHANGE_REQUESTS: 'Change Request',
  CANCEL_REQUESTS: 'Cancel Request',
  FILL_RESPONSES: 'Fill Response',
  RX_FAILED: 'Rx Failed',
  FAILURE_CONSTANTS: 'Failure Constants',
  PRESCRIBED_DRUGS: 'Prescribed Drugs',
  DATE: 'Date',
  FROM: 'From',
  TO: 'To',
  MEDICATION_INFORMATION: 'Medication Information',
  ORDERED_MEDICATION: 'Ordered Medication',
  PT_INSTRUCTION: 'Pt. Instruction',
  QUENTITY: 'Quentity',
  DISPENSE_FROM: 'Dispense From',
  REFILL: 'Refill',
  ALLOW_SUBSTITUTION: 'Allow Substitution',
  WRITTEN_ON: 'Written on',
  PHARMACY_NOTE: 'Pharmacy Note',
};

export const notificationConstants = {
  NOTIFICATION: 'Notification',
  TODAY: 'Today',
  TELEHEALTH: 'Telehealth',
  PAID: 'Paid',
  APPOINTMENT_REQUEST: 'Appointment Request',
  YESTERDAY: 'Yesterday',
  RESHEDULE: 'Reshedule',
  DECLINE: 'Decline',
  ACCEPT: 'Accept',
  LAB_REPORT_UPDATED: 'Lab Report Updated',
  VIEW_YOUR_LAB_REPORT_PDF_HERE: 'View Your Lab Report PDF Here',
  NADYA_POPLOVETSC_ACCEPTED_YOUR_INVITATION: 'Nadya Poplovetsc Accepted your Invitation',
  PAYMENT_COLLECTION: 'Payment Collection',
  CLICK_HERE_TO_COMPLETE_YOUR_TRANSACTION: 'Click Here To Complete your Transaction',
};
