export const patientsConstants = {
  PATIENTS: 'Patients',
  IMPORT_OR_EXPORT: 'Import/Export',
  STATUS: 'Status',
  SELECT_STATUS: 'Select Status',
  NEW_PATIENT: 'New Patient',
  IMPORT_CSV: 'Import CSV',
  EXPORT_CSV: 'Export CSV',
  EXPORT_CCDA: 'Export CCDA',
  PRINT: 'Print',
  SEARCH_PATIENT: 'Search Patient',
  BALANCE: 'Balance',
  PATIENT: 'Patient',
  INSURANCE: 'Insurance',
  FLAG: ' Flag',
  PATIENT_PORTAL: 'Patient Portal (Last Log)',
  VIEW_PATIENT_PORTAL: 'View Patient Portal',
  EDIT_PATIENT_FLAG: 'Edit Patient Flag',
  PATIENT_FLAG: 'Patient Flag',
  SELECT_PATIENT_FLAG: 'Select Patient Flag',
  DEMOGRAPHICS: 'Demographics',
};

export const formsConstants = {
  SAVE: 'Save',
  CANCEL: 'Cancel',
  UPDATING: 'Updating',
  ADDING: 'Adding',
  UPDATE: 'Update',
  ADD: 'Add',
  ASSIGN_TO_PATIENT: 'Assign to Patient',
  EDIT: 'Edit',
  ARCHIVE: 'Archive',
  UPLOADING: 'Uploading',
  RESTORE: 'Restore',
  CHECK_ELIGIBILITY:'Check Eligibility',
    SEND:'Send'

};

export const addPatientConstants = {
  ADD_SIGN: 'Add Signature',
  ADD_PATIENT: 'Add Patient',
  EDIT_PATIENT: 'Edit Patient',
  EDIT_PROFILE: 'Edit Profile',
  PATIENT_INFORMATION: 'Patient Information',
  PATIENT_DETAILS: 'Patient Details',
  CONTACT_INFORMATION: 'Contact Information',
  EMERGENCY_CONTACT_INFORMATION: 'Emergency Contact Information',
  INSURANCE: 'Insurance',
  OTHERS: 'Others',
  PROFILE_PICTURE: 'Profile Picture',
  UPLOAD: 'Upload',
  FIRST_NAME: 'First Name',
  ENTER_FIRST_NAME: 'Enter First Name',
  MIDDLE_NAME: 'Middle Name',
  ENTER_MIDDLE_NAME: 'Enter Middle Name',
  LAST_NAME: 'Last Name',
  ENTER_LAST_NAME: 'Enter Last Name',
  STATUS: 'Status',
  SELECT_STATUS: 'Select Status',
  NAME: 'Name',
  ENTER_NAME: 'Enter Name',
  DATE_OF_BIRTH: 'Date Of Birth',
  CHOOSE_DATE: 'Choose Date',
  PHONE_NUMBER: 'Phone Number',
  ENTER_PHONE: 'Enter Phone Number',
  GENDER: 'Gender',
  SELECT_GENDER: 'Select Gender',
  MARITAL_STATUS: 'Marital Status',
  SELECT_MARITAL_STATUS: 'Select Marital Status',
  TIME_ZONE: 'Timezone',
  SELECT_TIMEZONE: 'Select Timezone',
  LANGUAGE: 'Language',
  SELECT_LANGUAGE: 'Select Language',
  SSN: 'SSN (Last 4 Digit)',
  ENTER_SSN: 'Enter Last 4 Digit',
  RACE: 'Race',
  ENTER_RACE: 'Enter Race',
  ETHNICITY: 'Ethnicity',
  ENTER_ETHNICITY: 'Enter Ethnicity',
  REGISTRATION_DATE: 'Registration Date',
  PROOF_OF_ID: 'Proof Of ID',
  SELECT_PROOF_OF_ID: 'Select Proof of Id',
  ID_NUMBER: 'ID Number',
  ENTER_ID_NUMBER: 'Enter ID Number',
  ADD_MORE: 'Add More',
  UPLOAD_PROOF_OF_ID: 'Upload Proof Of Id',
  UPLOAD_FRONT_VIEW: 'Upload Front View',
  UPLOAD_BACK_VIEW: 'Upload Back View',
  DRAG_AND_DROP_FILES: 'Drag & Drop Your Files or, Browse',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter Email',
  FAX_NUMBER: 'Fax Number',
  ADDRESS_LINE_1: 'Address Line 1',
  ENTER_ADDRESS_LINE_1: 'Enter Address Line 1',
  ADDRESS_LINE_2: 'Address Line 2',
  ENTER_ADDRESS_LINE_2: 'Enter Address Line 2',
  CITY: 'City',
  ENTER_CITY: 'Enter City',
  STATE: 'State',
  SELECT_STATE: 'Select State',
  ZIP_CODE: 'Zip Code',
  ENTER_ZIP_CODE: 'Enter Zip Code',
  EMERGENCY_CONTACT: 'Emergency Contact',
  RELATIONSHIP_WITH_PATIENT: 'Relationship with Patient',
  SELECT_RELATIONSHIP: 'Select Relationship',
  CLINICIAN_INFORMATION: 'Clinician Information',
  PRIMARY_CLINICIAN: 'Primary Clinician',
  REFERRING_CLINICIAN: 'Referring Clinician',
  INSURANCE_DETAILS: 'Insurance Details',
  GUARDIAN_INFORMATION: 'Guardian Infomation',
  KEEP_SAME_INFORMATION_AS_EMERGENCY_CONTACT: 'Keep Same Information As Emergency Contact',
  PHONE_APPPOINTMENT_REMINDERS: 'Phone Appointment Reminders',
  EMAIL_APPPOINTMENT_REMINDERS: 'Email Appointment Reminders',
  INSURANCE_TYPE: 'Insurance Type',
  SELECT_INSURANCE_TYPE: 'Select Insurance Type',
  INSURANCE_NAME: 'Insurance Name',
  SELECT_INSURANCE_NAME: 'Select Insurance Name',
  MEMBER_ID: 'Member ID',
  ENTER_MEMBER_ID: 'Enter Member ID',
  PLAN_NAME: 'Plan Name',
  ENTER_PLAN_NAME: 'Enter Plan Name',
  PLAN_TYPE: 'Plan Type',
  SELECT_PLAN_TYPE: 'Select Plan Type',
  GROUP_ID: 'Group ID',
  ENTER_GROUP_ID: 'Enter Group ID',
  GROUP_NAME: 'Group Name',
  ENTER_GROUP_NAME: 'Enter Group Name',
  EFFECTIVE_START_DATE_AND_END_DATE: 'Effective Start Date And End Date',
  CHOOSE_START_AND_END_DATE: 'Choose Start And End Date',
  PATIENT_RELATIONSHIP_TO_INSURED: '',
  UPLOAD_INSURANCE_CARD: 'Upload Insurance Card',
  ADD_SECONDARY_INSURANCE: 'Add Secondary Insurance',
  REMOVE_SECONDARY_INSURANCE: 'Remove Secondary Insurance',
  PROVIDER_INFORMATION: 'Provider Information',
  PRIMARY_PROVIDER: 'Primary Provider',
  SELECT_PRIMARY_PROVIDER: 'Select Primary Provider',
  PROVIDER_GROUP_LOCATION: 'Provider Group Location',
  SELECT_PROVIDER_GROUP_LOCATION: 'Select Provider Group Location',
  PREFERENCES: 'Preferences',
  PHARMACY: 'Pharmacy',
  SEARCH_AND_SELECT_PHARMACY: 'Search and Select Pharmacy',
  ADD_NEW: 'Add New',
  LAB_NAME: 'Lab Name',
  SEARCH_AND_SELECT_LAB: 'Search and Select Lab',
  RADIOLOGY: 'Radiology',
  SEARCH_AND_SELECT_RADIOLOGY: 'Search and Select Radiology',
  LOUIS_AND_CLARK_DRUG: 'Louis and Clark Drug',
  PREFERRED_COMMUNICATION: 'Preferred Communication',
  COMMUNICATION_METHOD: 'Communication Method',
  SLEECT_COMMUNICATION_METHOD: 'Select Communication Method',
  START_DATE: 'Start Date',
  SELF_PAY: 'Self Pay',
  END_DATE: 'End Date',
  ENTER_END_DATE: 'Enter End Date',
  ENTER_START_DATE: 'Enter Start Date',
  ENTER_INSURANCE_NAME: 'Enter Insurance Name',
  PRIMARY_INSURANCE: 'Primary Insurance',
  SUBSCRIBER_DETAILS: 'Subscriber Details',
  CLIENT_RELATIONSHIP_WITH_SUBSCRIBER: 'Client Relationship with Subscriber',
  UPLOAD_INSURANCE_CARD_FRONT: 'Upload Insurance Card Front',
  UPLOAD_INSURANCE_CARD_BACK: 'Upload Insurance Card Back',
  SECONDARY_INSURANCE: 'Secondary Insurance',
  SELECT_PRIMARY_CLINICIAN: 'Select Primary Clinician',
  SELECT_REFERRING_CLINICIAN: 'Select Referring Clinician',
  PATIENT_REGISTERED_PROVIDER_GROUP_LOCATION: 'Registered Provider Group Location',
  PATIENT_ID: 'ID',
  PATIENT_EMERGENCY_CONTACT_NUMBER: 'Emergency Contact',
  LANGUAGES: 'Languages',
  COUNTRY: 'Country',
  ADDRESS: 'Address',
  PRIVACY: 'Privacy',
  CONSENT_FORM: 'Consent Form',
  CONSENT_TO_VOICE_CALL: 'Consent To Voice Call',
  CONSENT_TO_VIDEO_CALL: 'Consent To Video Call',
  CONSENT_TO_TEXT: 'Consent To Text',
  NOTE: 'Note',
  PREFERRED_PROVIDER: 'Preferred Provider',
  DEFAULT_PHARMACY: 'Preferred Pharmacy',
  PREFERRED_LAB: 'Preferred Lab',
  PREFERRED_RADIOLOGY: 'Preferred Radiology',
  PHARMACY_ADDRESSES: 'Pharmacy Addresses',
  SUBSCRIBER_FIRST_NAME: 'Subscriber First Name',
  SUBSCRIBER_LAST_NAME: 'Subscriber Last Name',
  SUBSCRIBER_DATE_OF_BIRTH: 'Subscriber Date Of Birth',
  FLAGS: 'Flags',
  EMAIL_ID: 'Email ID',
  EMEGENCY_CONTACT_DETAILS: 'Emergency Contact Details',
  RELATIONSHIP: 'Relationship',
  SIGNATURE: 'Signature',
};

export const pharmacyLabRadiologyConstants = {
  PHARMACY_NAME: 'Pharmacy Name',
  ENTER_PHARMACY_NAME: 'Enter Pharmacy Name',
  LAB_NAME: 'Lab Name',
  ENTER_LAB_NAME: 'Enter Lab Name',
  RADIOLOGY_NAME: 'Radiology Name',
  ENTER_RADIOLOGY_NAME: 'Enter Radiology Name',
  ADDRESS_LINE_1: 'Address Line 1',
  ENTER_ADDRESS_LINE_1: 'Enter Address Line 1',
  ADDRESS_LINE_2: 'Address Line 2',
  ENTER_ADDRESS_LINE_2: 'Enter Address Line 2',
  PHONE_NUMBER: 'Phone Number',
  ENTER_PHONE_NUMBER: 'Enter Phone Number',
  FAX_NUMBER: 'Fax Number',
  ENTER_FAX_NUMBER: 'Enter Fax Number',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter Email',
  CITY: 'City',
  ENTER_CITY: 'Enter City',
  STATE: 'State',
  SELECT_STATE: 'Select State',
  ZIP_CODE: 'Zip Code',
  ENTER_ZIP_CODE: 'Enter Zip Code',
  COUNTRY: 'Country',
};

export const patientDashboardConstants = {
  ALLERGIES: 'Allergies',
  DIAGNOSES: 'Diagnoses',
  MEDICATIONS: 'Medications',
  LAB_RESULTS: 'Lab Results',
  RADIOLOGY_RESULTS: 'Radiology Results',
  PROBLEMS: 'Problems',
  PROCEDURES: 'Procedures',
  MEDICAL_HISTORY: 'Medical History',
  ADD_ALLERGY: 'Add Allergy',
  EDIT_ALLERGY: 'Edit Allergy',
  ADD_DIAGNOSIS: 'Add Diagnosis',
  EDIT_DIAGNOSIS: 'Edit Diagnosis',
  FAMILY_HISTORY: 'Family History',
  ADD_FAMILY_HISTORY: 'Add Family History',
  EDIT_FAMILY_HISTORY: 'Edit Family History',
  ADD_MEDICAL_HISTORY: 'Add Medical History',
  EDIT_MEDICAL_HISTORY: 'Edit Medical History',
  SURGERICAL_HISTORY: 'Surgical History',
  ADD_SURGERICAL_HISTORY: 'Add Surgical History',
  EDIT_SURGERICAL_HISTORY: 'Edit Surgical History',
  ADD_MEDICATION: 'Add Medication',
  EDIT_MEDICATION: 'Edit Medication',
  UPCOMMING_APPOINTMENTS: 'Upcomming ',
  PAST_APPOINTMENTS: 'Past',
};

export const addAllergyConstants = {
  ALLERGY_TYPE: 'Allergy Type',
  ALLERGY_NAME: 'Allergy Name',
  REACTION: 'Reaction',
  SEVERITY: 'Severity',
  SELECT_DIAGNOSIS_NAME: 'Select Diagnosis Name',
  SELECT_REACTION: 'Select Reaction',
  SELECT_SEVERITY: 'Select Severity',
  ONSET_DATE: 'Onset Date',
  CHOOSE_DATE: 'Choose Date',
  TYPE_HERE: 'Type here',
  NOTE: 'Note',
  STATUS: 'Status',
  SELECT_STATUS: 'Select Status',
  TYPE: 'Type',
  SELECT_TYPE: 'Select Type',
};

export const historyConstants = {
  MEDICINE_NAME: 'Medicine Name',
  ENTER_MEDICINE_NAME: 'Enter Medicine Name',
  SIG: 'Sig',
  ENTER_SIG: 'Enter Sig Quantity',
  BY_ORAL_ROUTE: 'By Oral Route',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  PROBLEM_NAME: 'Problem Name',
  ENTER_PROBLEM_NAME: 'Enter Problem Name',
  RELATIVE: 'Relative',
  SELECT_RELATIVE: 'Select Relative',
  ONSET_AGE: 'Onset Age',
  ENTER_ONSET_AGE: 'Enter Onset Age',
  DIED: 'Died',
  CONDITION_NAME: 'Condition Name',
  ENTER_CONDITION_NAME: 'Enter Condition Name',
  ONSET_DATE: 'Onset Date',
  ENTER_ONSET_DATE: 'Enter Onset Date',
  SURGERY_NAME: 'Surgery Name',
  ENTER_SURGERY_NAME: 'Enter Surgery Name',
  SURGERY_DATE: 'Surgery Date',
  ENTER_SURGERY_DATE: 'Enter Surgery Date',
  SURGERY_TYPE: 'Surgery Type',
  SELECT_SURGERY_TYPE: 'Select Surgery Type',
  NOTE: 'Note',
  ENTER_NOTE: 'Enter Note',
  TYPE_HERE: 'Type here',
  NO_FAMILY_HISTORY_RECORDED: 'No family history recorded',
  NO_MEDICAL_HISTORY_RECORDED: 'No medical history recorded',
  NO_SURGERICAL_HISTORY_RECORDED: 'No surgical history recorded',
  NO_DIAGNOSIS_RECORDED: 'No diagnoses recorded',
  NO_ALLERGY_RECORDED: 'No allergies recorded',
  NO_MEDICATION_RECORDED: 'No medications recorded',
};

export const paymentCardConstants = {
  CREDIT_CARD: 'Credit Card ',
  EXPIRATION_DATE: 'Expiration Date',
  DEFAULT: 'Default',
  STATUS: 'Status',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  CREDIT_CARD_NUMBER: 'Credit Card Number (xxxx xxxx 1234)',
  ENTER_CREDIT_CARD_NUMBER: 'Enter Credit Card Number ',
  CREDIT_CARD_NAME: 'Credit Card Name',
  ENTER_CREDIT_CARD_NAME: 'Enter Credit Card Name',
  EXPIRATION_DATE_MM_YY: 'Expiration Date (MM/YY)',
  ENTER_EXPIRATION_DATE: 'Enter Expiration Date',
  ADD_CARD: 'Add Card',
  CARD_DETAILS: 'Card Details',
  CARD_NUMBER: 'Card Number',
  ENTER_CARD_NUMBER: 'Enter Card Number',
  CARD_NAME: 'Card Name',
  ENTER_CARD_NAME: 'Enter Card Name',
  SELECT_STATUS: 'Select Status',
  SET_AS_PRIMARY_CARD: 'Set as Primary Card',
  CREDIT_CARD_NUMBER_IS_REQUIRED: 'Credit Card Number is required',
  CREDIT_CARD_NAME_IS_REQUIRED: 'Credit Card Name is required',
  EXPIRATION_DATE_IS_REQUIRED: 'Expiration Date is required',
  STATUS_IS_REQUIRED: 'Status is required',
  STATUS_CHANGES_SUCCSSFULLY: 'Status changed successfully',
  OERATION_COM_SUCCSSFULLY: 'Operation completed successfully',
  CHANGE_STATUS: 'Change Status',
  NO_CARDS_FOUND: 'No payment cards found',
};

export const providerConstants = {
  PROFILE_SETTINGS: 'Profile Settings',
  INSURANCE: 'Insurance',
  NO_CLINICS_ASSOCIATED: 'No Clinics Associated',
  NO_LOCATIONS_ASSOCIATED: 'No Locations Associated',
  ADD_CLINIC: 'Add Clinic',
  LOADING_PROFILE: 'Loading profile...',
  PROFILE_DETAILS: 'Profile Details',
  APPOINTMENT_DETAILS: 'Appointment Details',
  EDIT_APPOINTMENT: 'Edit Appointment',
  CLINICIAN_INFORMATION: 'Clinician Information',
  EDIT_CLINIC: 'Edit Clinic',
  RESCH_APPOINTMENT: 'Reschedule Appointment',
  VIEW_PATIENT_INTAKE: 'View Patient Intake',
};

export const appointmentConstants = {
  REASON_FOR_VISIT: 'Reason for Visit',
  ADD_REASON: 'Add Reason...',
  STATUS: 'Status',
  SELECT_STATUS: 'Select Status',
  REASON: 'Reason',
  ENTER_REASON: 'Enter Reason...',
  VIRTUAL_ENCOUNTER: 'Virtual Encounter',
  IN_PERSON_ENCOUNTER: 'In-Person ',
  APPOINTMENT_MODE: 'Appointment Mode',
  APPOINTMENT_TYPE: 'Appointment Type',
  CLINICIAN: 'Clinician',
  DATE_TIME: 'Date & Time',
  DURATION: 'Duration',
  FORMS: 'Forms',
  VIEW_AUTHORIZATION: 'View Authorization',
  INTAKE_FORM:'Intake Form',
  CONSENT_FORM:"Consent Form",
  CHECK_ELIGIBILITY:'Check Eligibility',
  START_VISIT_NOTE:'Start Visit Note',
  CHECK_IN:'Check In',
  COLLECT_PAYMENT:'Collect Payment',
  COMPLETE_CHECK_IN:'Complete Check In',
  BACK:'Back',
};

export const documentsConstants = {
  DOCUMENTS: 'Documents',
  MANAGE_DOCUMENT_TYPES: 'Manage Document Types',
  UPLOAD_DOCUMENTS: 'Upload Documents',
  STICKY_NOTES: 'Sticky Notes',
  ADD_STICKY_NOTE: 'Add Sticky Note',
  EDIT_STICKY_NOTE: 'Edit Sticky Note',
  STICKY_NOTE: 'Sticky Note',
  ENTER_STICKY_NOTE: 'Enter Sticky Note',
  STICKY_NOTE_TITLE: 'Sticky Note Title',
  ENTER_STICKY_NOTE_TITLE: 'Enter Sticky Note Title',
  STICKY_NOTE_CONTENT: 'Sticky Note Content',
  ENTER_STICKY_NOTE_CONTENT: 'Enter Sticky Note Content',
  EDIT_DOCUMENT: 'Edit Document',
  ASSIGN_DOCUMENT: 'Assign Document',
  ARCHIVE_DOCUMENT: 'Archive Document',
  DOCUMENT_TYPE: 'Document Type',
  SELECT_DOCUMENT_TYPE: 'Select Document Type',
  DOCUMENT_DATE: 'Date',
  CHOOSE_DATE: 'Choose Date',
  DOCUMENT_NAME: 'Document Name',
  ENTER_DOCUMENT_NAME: 'Enter Document Name',
  UPLOAD_DOCUMENT: 'Upload Document',
  RESTORE_DOCUMENT: 'Restore Document',
  VIEW_DOCUMENT: 'View Document',
  DOCUMENT_INFORMATION: 'Document Information',
  DESCRIPTION: 'Description',
  DOCUMENT_PREVIEW: 'Document Preview',
  ADDITIONAL_DETAILS: 'Additional Details',
  PATIENT_ID: 'Patient ID',
  FILE_SIZE: 'File Size',
  UPLOADED_BY: 'Uploaded By',
  UPLOADED_AT: 'Uploaded At',
  DOCUMENT_FORMAT: 'Document Format',
  NO_DOCUMENT_SELECTED: 'No document selected',
  SAVE: 'Save',
};

export enum RequiredFieldLabels {
  INSURANCE_TYPE = 'Insurance type',
  INSURANCE_NAME = 'Insurance name is required',
  MEMBER_ID = 'Member ID is required',
  RELATIONSHIP = 'Relationship is required',
  FIRST_NAME = 'First name is required',
  LAST_NAME = 'Last name is required',
  DATE_OF_BIRTH = 'Date of birth is required',
  START_DATE = 'Start date is required',
  END_DATE = 'End date is required',
}
