export const profile = {
  PROFILE: 'Profile',
  PROFILE_PICTURE: 'Profile Picture',
  CANCEL: 'Cancel',
  CHANGE_PASSWORD: 'Change Password',
  LOGOUT: 'Logout',
  LOGOUT_CONFIRMATION: 'Are you sure?',
  LOGOUT_CONFIRMATION_MESSAGE: 'You will be logging out of the software',
  LOGOUT_CONFIRMATION_MESSAGE_2: 'and need password to login again.',
  SIGNATURE_PAD: 'Signature Pad',
  UPDATE_SIGNATURE: 'Update Signature',
};

export const settingsConstants = {
  SETTINGS: 'Settings',
  APPOINTMENT: 'Appointment',
  AVAILABILITY: 'Availability',
  APPOINTMENT_TYPES: 'Appointment Types',
  COLOR_CONFIGURATION: 'Color Configuration',
  CANCELLATION_POLICY: 'Cancellation Policy',
  PROVIDER_ACCOUNT: 'Clinician Account',
  PROFILE: 'Profile',
  PROVIDER_GROUP: 'Provider Group',
  PATIENT_FLAG: 'Patient Flag',
  PRACTICE: 'Practice',
  LOCATIONS: 'Locations',
  USERS: 'Users',
  ROLES_AND_RESPONSIBILITY: 'Roles & Responsibility',
  PRINT_CONFIGURATION: 'Print Configuration',
  MASTER: 'Master',
  DATA_IMPORT: 'Data Import',
  PROVIDER_DATA: 'Provider Data',
  PATIENT_DATA: 'Patient Data',
  ICD_10_CODE: 'ICD 10 Code',
  CPT_CODE: 'CPT Code',
  TEMPLATES: 'Templates',
  VISIT_NOTES: 'Visit Notes',
  REVIEW_OF_SYSTEMS: 'Review of Systems ',
  PHYSICAL_EXAM: 'Physical Exam',
  MACROS: 'Macros',
  ANNOTABLE_IMAGE: 'Annotable Image',
  BILLING: 'Billings',
  SERVICES: 'Sevices (Fee Schedule)',
  ACCOUNT_SETUP: 'Account Setup',
  PATIENT_PAYMENT: 'Patient Payment',
  INVOICE_TEMPLATE: 'Invoice Template',
  RECEIPT_TEMPLATE: 'Receipt Template',
  CALENDER_PAYMENT_COLLECTION: 'Calender Payment Collection',
  APPT_NAME: 'Appointment Name',
  ENTER_APPT_NAME: 'Enter Appointment Name',
  COLOR: 'Color',
  SELECT_COLOR: 'Select Color',
  EDIT_COLOR_CONFIG: 'Edit Color Configuration',
};

export const practiceSettingConstants = {
  PRACTICE_SETTINGS: 'Practice Settings',
  PROFILE: 'Profile',
  LOCATION: 'Location',
  USERS: 'Users',
  ROLES_AND_RESPONSIBILITY: 'Roles & Responsibility',
  PRINT_CONFIGURATION: 'Print Configuration',
  EDIT_DETAILS: 'Edit Details',
  ADD_NEW_LOCATION: 'Add New Location',
  ADD_PROVIDER_USER: 'Add Provider User',
  ADD_STAFF_USER: 'Add Staff User',
  ADD_NEW_PRINT_CONFIGURATION: 'Add New Print Configuration',
};

export const providerSettingConstants = {
  PROVIDER_SETTINGS: 'Clinician Profile',
  PROFILE: 'Profile',
  CLINIC: 'Clinic',
  PATIENT_FLAG: 'Patient Flag',
  EDIT_DETAILS: 'Edit Details',
  ADD_NEW_PATIENT_FLAG: 'Add New Patient Flag',
};

export const appointmentSettingConstants = {
  APPOINTMENT_SETTINGS: 'Appointment Settings',
  AVAILABILITY: 'Availability',
  APPOINTMENT_TYPES: 'Appointment Types',
  AVAILABILITY_TYPE: 'Availability Type',
  COLOR_CONFIGURATION: 'Color Configuration',
  EDIT_AVAILABILITY: 'Edit Availability',
  RAFAELA_TILTON: 'Rafaela Tilton',
  LOCATION: 'Location',
  NEW: 'New',
  IN_PERSON_NEW_PATIENT: 'In-Person New Patient',
  COLOR_CODE: 'Color Code',
  APPOINTMENT_TYPE_TITLE: 'Appointment Type Title',
  DESCRIPTION: 'Description',
  APPOINTMENT_DURATION: 'Appointment Duration',
  PROCEDURE_CODE: 'Procedure Code',
  SELECT_CODE: 'Select Code',
  MODIFIER: 'Modifier',
  ATTACH_FORMS: 'Attach Forms',
  ADD: 'Add',
  SAVE: 'Save',
  CANCEL: 'Cancel',
};

export const templateSettingConstants = {
  TEMPLATES: 'Templates',
  CREATE_NEW_TEMPLATE: 'Create New Template',
  CREATE_NEW_ROS: 'Create New ROS',
  CREATE_NEW_PE: 'Create New PE',
  CREATE_NEW_MACRO: 'Create New Macro',
  UPLOAD_IMAGE: 'Upload Image',
};

export const masterSettingConstants = {
  UPLOAD_DATA: 'Upload Data',
  ADD_ICD_10_CODE: 'Add ICD 10 Code',
  ADD_CPT_CODE: 'Add Procedure Code',
  SEARCH_HERE: 'Search Here',
};

export const billingSettingConstants = {
  FEE_SCHEDULE: 'Fee Schedule',
  STATUS: 'Status',
  SELECT_CPT_HCPCS_PROCEDURE_CODE: 'Search Procedure Code',
  ADD_FEE_SCHEDULE: 'Add Fee Schedule',
  EDIT_FEE_SCHEDULE: 'Edit Fee Schedule',
};

export const formConstants = {
  ADD_NEW_LOCATION_FOR: 'Add New Location For',
  PROCEDURE_CODE: 'Procedure Code',
  RATE: 'Rate',
  CODE_DESCRIPTION: 'Code Description',
  STATUS: 'Status',
  ADD_Location_LOGO: 'Add Location Logo',
  LOCATION_NAME: 'Location Name',
  ENTER: 'Enter',
  SELECT: 'Select',
  LOCATION_ID: 'Location ID',
  CONTACT_NUMBER: 'Contact Number',
  CONTACT_PERSON: 'Contact Person',
  ENTER_CONTACT_PERSON_NAME: 'Enter Contact Person Name',
  PLACE_OF_SERVICE: 'Place of Service',
  SPECIALITY_TYPE: 'Speciality Type',
  EMAIL_ID: 'Email ID',
  TIME_ZONE: 'Time Zone',
  GROUP_NPI_NUMBER: 'Group NPI Number',
  FAX_ID: 'Fax ID',
  INFORMATION: 'Information',
  ID_QUALIFIER: 'Id qualifier',
  NUMBER: 'Number',
  ADDRESS: 'Address',
  PHYSICAL_ADDRESS: 'Physical Address',
  BILLING_ADDRESS: 'Billing Address',
  ADDRESS_1: 'Address 1',
  ADDRESS_2: 'Address 2',
  CITY: 'City',
  STATE: 'State',
  COUNTRY: 'Country',
  ZIP_CODE: 'Zip Code',
  SAVE: 'Save',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
  APPT_NAME_REQ: 'Appointment Name is required',
  APPT_COLOR_REQ: 'Appointment Color is required',
  ADD_APPT_TYPE: 'Add Appointment Type',
  EDIT_APPT_TYPE: 'Edit Appointment Type',
  APPR_TYPE_REQ: 'Appointment type is required',
  DURATION_REQ: 'Duration is required',
  COLOR_REQ: 'Color is required',
  APPOINTMENT_TYPE: 'Appointment Type',
  COLOR_CODE: 'Color Code',
  DESCRIPTION: 'Description',
  DURATION: 'Duration',
  TIME: 'Time',
  APPOINTMENT_TYPE_TITLE: 'Appointment Type Title',
  SELECT_COLOR: 'Select Color',
  DOCUMENT_TYPES: 'Document Types',
  MODIFIER: 'Modifier',
  RATE_REQ: 'Rate is required',
  RATE_POSITIVE: 'Rate must be greater than 0',
  PROCEDURE_CODE_REQ: 'Procedure code is required',
  SELECT_CODE: 'Select Code',
  ENTER_RATE: 'Enter Rate',
  SELECT_STATUS: 'Select Status',
  ENTER_CODE_DESCRIPTION: 'Enter Code Description',
  SELECT_APPT_TYPE: 'Select Appointment Type',
};

export const templateConstants = {
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  ROS_created_successfully: 'ROS created successfully',
  PE_created_successfully: 'PE created successfully',
  ROS_updated_successfully: 'ROS updated successfully',
  PE_updated_successfully: 'PE updated successfully',
  ROS_deleted_successfully: 'ROS deleted successfully',
  PE_deleted_successfully: 'PE deleted successfully',
  ROS_cloned_successfully: 'ROS cloned successfully',
  PE_cloned_successfully: 'PE cloned successfully',
  QUESTIONS_BY_EHR: 'Questions by EHR',
  CLICK_OR_DRAG_DROP_INTO_FORM_ON_RIGHT: 'Click or drag & drop into form on right',
  ADD_AT_LEAST_ONE_CATEGORY: 'Please add at least one {componentType} category',
  DRAG_AND_DROP_CATEGORIES_FROM_LEFT:
    'Drag and drop categories from the left or click on them to add to the form',
  TITLE_IS_REQUIRED: 'Title is required',
  CLONE_PE_TEMPLATE: 'Clone PE Template',
  ERROR_CLONING_ROS: 'Error cloning ROS',
  CLONING: 'Cloning...',
  CLONE: 'Clone',
  CANCEL: 'Cancel',
  ERROR_FETCHING_PE_DATA: 'Error fetching PE data',
  ERROR_DELETING_PE: 'Error deleting PE',
  ERROR_CLONING_PE: 'Error cloning PE',
  TEMPLATE_NAME: 'Template Name',
  ENTER_TEMPLATE_NAME: 'Enter Template Name',
  CLONE_VISIT_NOTE_TEMPLATE: 'Clone Visit Note Template',
  CLONE_VISIT_NOTE_TEMPLATE_SUCCESS: 'Visit Note Template cloned successfully',
  VISIT_NOTE: 'Visit Notes',
  REVIEW_OF_SYSTEMS: 'Review of Systems',
  PHYSICAL_EXAM: 'Physical Exam',
  MACROS: 'Macros',
  INTAKE_FORM: 'Intake Form',
  CONSENT_FORM: 'Consent Form',
  ADD_ROS: 'Add ROS',
  ADD_PE: 'Add PE',
  ADD_MACRO: 'Add Macro',
  ADD_VISIT_NOTE: 'Add Visit Note',
  SEARCH_BY_TITLE: 'Search by Title',
  SEARCH_BY_ROS_TITLE: 'Search by ROS Title',
  SEARCH_BY_PE_TITLE: 'Search by PE Title',
  SEARCH_BY_MACRO_TITLE: 'Search by Macro Title',
  SEARCH_BY_LOC_TITLE: 'Search by Loc Title',
  SEARCH_BY_NAME: 'Search by Template Name',
  TEMPLATES: 'Templates',
  TYPE: 'Type',
  STATUS: 'Status',
  ALL: 'All',
  CONSULTATION_NOTE: 'Consultation Note',
  SIMPLE_NOTE: 'Simple Note',
  SOAP_NOTE: 'Soap Note',
  CLONE_ROS_TEMPLATE: 'Clone ROS Template',
  BASIC_INFORMATION: 'Basic Information',
  TEMPLATE_DATA: 'Template Data',
  TEMPLATE_TYPE: 'Template Type',
  VITALS: 'Vitals',
  PROCEDURE_CODES: 'Procedure Codes',
  ICD_CODES: 'ICD Codes',
  PATIENT_CONSENT_FORM: 'Patient Consent Form',
  FINANCIAL_RESPONSIBILITY: 'Financial Responsibility/ Assignment of Benefits',
  TREAT_PHOTO_CONSENT: 'Treat/Photo Consent',
  PATIENT_AUTHORIZATION_OF_DISCLOSURE: 'Patient Authorization of Disclosure',
  ACKNOWLEDGEMENT_OF_RECEIPT_OF_NOTICE_OF_PRIVACY_RULES:
    'Acknowledgement of Receipt of Notice of Privacy Rules',
  MEDICAL_APPOINTMENT_CANCELLATION: 'Medical Appointment Cancellation/No Show Policy',
  PATIENT_SIGNATURE: 'Patient Signature',
  PATIENT_GUARDIAN_SIGNATURE: 'Patient/ Guardian Signature',
  RELATIONSHIP_TO_PATIENT: 'Relationship to Patient',
  PATIENT_NAME: 'Patient/ Guardian Name',
  DATE: 'Date',
  SELECT_RELATIONSHIP_TO_PATIENT: 'Select Relationship to Patient',
  ENTER_NAME: 'Enter Patient/ Guardian Name',
  SELECT_DATE: 'Select Date',
  PATIENT_HEALTH_HISTORY: 'Patient Health History',
  FAMILY_HEALTH_HISTORY: 'Family Health History',
  HEALTH_HABIT_AND_PERSONAL_SAFETY: 'Health Habit and Personal Safety',
  WOMEN_ONLY: 'Women Only',
  MEN_ONLY: 'Men Only',
  PHONE_NUMBER: 'Phone Number',
  ENTER_PHONE_NUMBER: 'Enter Phone Number',
  MOBILE_TELEPHONE: 'Mobile Telephone',
  ENTER_MOBILE_TELEPHONE: 'Enter Mobile Telephone',
  HOME_TELEPHONE: 'Home Telephone',
  ENTER_HOME_TELEPHONE: 'Enter Home Telephone',
  WORK_TELEPHONE: 'Work Telephone',
  ENTER_WORK_TELEPHONE: 'Enter Work Telephone',
  AGE: 'Age',
  ENTER_AGE: 'Enter Age',
  GENDER: 'Gender',
  SELECT_GENDER: 'Select Gender',
  SIGNIFICANT_HEALTH_PROBLEM: 'Significant Health Problem',
  ENTER_SIGNIFICANT_HEALTH_PROBLEM: 'Enter Significant Health Problem',
  SAVE_AS_DRAFT: 'Save as Draft',
  SAVE: 'Submit',
  SAVE_AND_NEXT: 'Save & Next',
  UPDATE_STATUS: 'Allow Patient to Refill',
  CONFIRM_POP: 'Do you really want to change this status to Draft?',
};

export enum MinMaxFieldLimits {
  INSURANCE_NAME_MIN = 'Insurance name must be at least 2 characters',
  MEMBER_ID_MIN = 'Member ID cannot be empty',
  MEMBER_ID_MAX = 'Member ID cannot exceed 50 characters',
  FIRST_NAME_MIN = 'First name must be at least 2 characters',
  FIRST_NAME_MAX = 'First name cannot exceed 50 characters',
  LAST_NAME_MIN = 'Last name must be at least 2 characters',
  LAST_NAME_MAX = 'Last name cannot exceed 50 characters',
}

export const InsuranceFormLabels = {
  PLEASE_SELECT_A_VALID_START_DATE: 'Please select a valid start date',
  PLEASE_SELECT_A_VALID_END_DATE: 'Please select a valid end date',
  END_DATE_MUST_BE_AFTER_START_DATE: 'End date must be after start date',
  FIRST_NAME_CAN_ONLY_CONTAIN_LETTERS_SPACES_HYPHENS_AND_APOSTROPHES:
    'First name can only contain letters, spaces, hyphens, and apostrophes',
  LAST_NAME_CAN_ONLY_CONTAIN_LETTERS_SPACES_HYPHENS_AND_APOSTROPHES:
    'Last name can only contain letters, spaces, hyphens, and apostrophes',
  PLEASE_ENTER_A_VALID_DATE: 'Please enter a valid date',
  DATE_OF_BIRTH_CANNOT_BE_IN_THE_FUTURE: 'Date of birth cannot be in the future',
  PLEASE_ENTER_A_REASONABLE_BIRTH_DATE: 'Please enter a reasonable birth date',
  PRIMARY_INSURANCE: 'Primary Insurance',
  SECONDARY_INSURANCE: 'Secondary Insurance',
  OTHER_INSURANCE: 'Other Insurance',
  INSURANCE: 'Insurance',
  INSURANCE_NAME: 'Insurance Name',
  SELECT_INSURANCE_NAME: 'Select Insurance Name',
  MEMBER_ID: 'Member ID',
  ENTER_MEMBER_ID: 'Enter Member ID',
  GROUP_ID: 'Group ID',
  ENTER_GROUP_ID: 'Enter Group ID',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  PATIENT_RELATIONSHIP: 'Client Relationship with Subscriber',
  SUBSCRIBER_DETAILS: 'Subscriber Details',
  UPLOAD_INSURANCE_CARD: 'Upload Insurance Card',
  INSURANCE_CARD_FRONT: 'Insurance Card Front',
  INSURANCE_CARD_BACK: 'Insurance Card Back',
  RELATIONSHIP: 'Relationship with Client',
};

export enum SUBSCRIBER_DETAILS_ENUM {
  SUBSCRIBER_NAME = 'Subscriber Name',
  FIRST_NAME = 'Subscriber First name',
  LAST_NAME = 'Subscriber Last name',
  DATE_OF_BIRTH = 'Subscriber Date of Birth',
  ENTER_FIRST_NAME = 'Enter first name',
  ENTER_LAST_NAME = 'Enter last name',
  FRONT_OF_CARD = 'Click here to upload or drag and drop front of card',
  BACK_OF_CARD = 'Click here to upload or drag and drop back of card',
}

export const ClientInsurnaceLables = {
  CLICK_TO_ADD_INSURANCE: "Click 'Add Insurance' to add your first insurance plan.",
  EDIT_INSURANCE: 'Edit Insurance',
  ADD_INSURANCE: 'Add Insurance',
  INSURANCE_DETAILS: 'Insurance Details',
  NO_INSURANCE_FOUND: 'No insurance plans found.',
  SET_PRIMARY: 'Set Primary',
  SET_SECONDARY: 'Set Secondary',
  PRIM_INS_CANNOT_BE_ARCHIVED: 'Primary insurance cannot be Archived',
  SEC_INS_CANNOT_BE_ARCHIVED: 'Secondary insurance cannot be Archived',
  ARCHIVE: 'Archive',
};

export const EligibilityLables = {
  NO_INSURANCE_FOUND: 'No insurance plans found.',
  ELIGIBILITY: 'Eligbility',
  ELIGIBILITY_CHECK: 'Eligibility Check',
  SELECT_APPT_TYPE:'Select Appointment Type',
  ELIGIBILTY_LAST_CHECKED: 'Eligibility Last Checked',
  SELECT_INSURANCE_TYPE: 'Select Insurance Type',
  SELECT_PROVIDER: 'Select Billing Clinician',
  SELECT_SERVICE: 'Select Service Type code',
  APPOINTMENT_TYPE: 'Appointment Type',
  SELECT_APPOINTMENT_TYPE: 'Select Appointment Type',
  BILLING_CLINICIAN: 'Billing Clinician',
  INSURANCE: 'Insurance',
  SELECT_INSURANCE: 'Select Insurance',
  SERVICE_TYPE_CODE: 'Service Type Code',
};
