export const todoTaskItemsData = [
  {
    heading: 'Review Electronic Claim Rejection',
    status: 'PENDING',
    profile: 'https://via.placeholder.com/30',
    name: 'Lesley Dobson',
    idDob: '#P1231 | 1-10-1965 (69) | Male',
    assignedBy: 'Roger Brooks',
    date: '12-03-2022',
  },
  {
    heading: 'Create a Progress Note for Therapy Session',
    status: 'PENDING',
    profile: 'https://via.placeholder.com/30',
    name: 'Leslie Alexander',
    idDob: '#P1231 | 1-10-1965 (69) | Male',
    assignedBy: 'Roger Brooks',
    date: '12-03-2022',
  },
  {
    heading: 'Process Portal Response',
    status: 'NEW',
    profile: 'https://via.placeholder.com/30',
    name: 'Devon Lane',
    idDob: '#P1231 | 1-10-1965 (69) | Male',
    assignedBy: 'Roger Brooks',
    date: '12-03-2022',
  },
  {
    heading: 'Create a Progress Note for Therapy Session',
    status: 'NEW',
    profile: 'https://via.placeholder.com/30',
    name: 'Kristin Watson',
    idDob: '#P1231 | 1-10-1965 (69) | Male',
    assignedBy: 'Roger Brooks',
    date: '12-03-2022',
  },
  {
    heading: 'Review Electronic Claim Rejection',
    status: 'NEW',
    profile: 'https://via.placeholder.com/30',
    name: 'Annette Black',
    idDob: '#P1231 | 1-10-1965 (69) | Male',
    assignedBy: 'Roger Brooks',
    date: '12-03-2022',
  },
];

export const messagesData = [
  {
    id: 1,
    avatar: '/placeholder-avatar.jpg',
    sender: 'Julianne Colony',
    preview: 'I attached my last blood...',
    time: 'Now',
    unreadCount: 2,
  },
  {
    id: 2,
    avatar: '/placeholder-avatar.jpg',
    sender: 'Leslie Alexander',
    preview: 'How are you...',
    time: '23 min ago',
  },
  {
    id: 3,
    avatar: '/placeholder-avatar.jpg',
    sender: 'Theresa Webb',
    preview: 'How are you...',
    time: '45 min ago',
  },
  {
    id: 4,
    avatar: '/placeholder-avatar.jpg',
    sender: 'Albert Flores',
    preview: 'How are you...',
    time: '1 hr ago',
  },
];

export const RENEWAL_REQUEST_MOCK_DATA = [
  {
    status: 'FAILED',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'CLOSED',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'PENDING',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const CHANGE_REQUEST_MOCK_DATA = [
  {
    status: 'NEW',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const CANCEL_REQUEST_MOCK_DATA = [
  {
    status: 'NEW',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const FILL_RESPONSES_MOCK_DATA = [
  {
    status: 'FAILED',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'FAILED',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const RESULT_AVAILABLE_MOCK_DATA = [
  {
    status: 'RESULT_READY',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEEDS_REVIEW',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'REOPENED',
    from: 'CarePlus Pharmacy',
    to: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const PENDING_MOCK_DATA = [
  {
    status: 'NEED_RESULT',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'PENDING',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEED_SUBMISSION',
    changeType: 'CarePlus Pharmacy',
    from: 'Teresa Lee',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const RESENT_SIGNED_MOCK_DATA = [
  {
    status: 'NEW',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'FAILED',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'CLOSED',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'PENDING',
    details: 'Approved by Pharmacy',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const UNMATCHED_MOCK_DATA = [
  {
    status: 'FAILED',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'CLOSED',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'NEW',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'PENDING',
    fillStatus: '',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const SEND_FAILURES_MOCK_DATA = [
  {
    status: 'FAILED',
    failureType: 'NewRx',
    from: 'CarePlus Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
  {
    status: 'FAILED',
    failureType: 'NewRx',
    from: 'HealthHub Pharmacy',
    patientName: 'Demelza Robins',
    medication: 'JLisinopril (Zestril, Prinivil)',
    lastUpdated: '12-03-2024, 07:25:40 PM',
  },
];

export const PATIENT_APPOINTMENT_MOCK_DATA = [
  {
    location: 'Virtual',
    time: '01:09 AM (15 mins)',
    appointmentType: 'New',
    profileIcon: 'https://i.pravatar.cc/150?img=4',
    patientName: 'Heena Robins',
    gender: 'F',
    dateOfBirth: '10-21-1959 (65)',
    contactDetails: '202-555-0188',
    providerName: 'Jacob Jones',
    chiefComplaint: 'Infection Disease',
    intakeForm: 'PENDING',
    insurance: 'COMPLETED',
  },
  {
    location: 'Location1',
    time: '01:09 AM (15 mins)',
    appointmentType: 'New',
    profileIcon: 'https://i.pravatar.cc/150?img=4',
    patientName: 'Demelza Robins',
    gender: 'M',
    dateOfBirth: '10-21-1959 (65)',
    contactDetails: '202-555-0188',
    providerName: 'Jacob Jones',
    chiefComplaint: 'Infection Disease',
    intakeForm: 'COMPLETED',
    insurance: 'COMPLETED',
  },
  {
    location: 'Location2',
    time: '01:09 AM (15 mins)',
    appointmentType: 'FollowUp',
    profileIcon: 'https://i.pravatar.cc/150?img=4',
    patientName: 'Demelza Robins',
    gender: 'M',
    dateOfBirth: '10-21-1959 (65)',
    contactDetails: '202-555-0188',
    providerName: 'Jacob Jones',
    chiefComplaint: 'Itching',
    intakeForm: 'SCHEDULED',
    insurance: 'FAILED',
  },
];

export const UNSIGNED_VISITS_MOCK_DATA = [
  {
    appointmentType: 'New',
    profileIcon: 'https://i.pravatar.cc/150?img=4',
    patientName: 'Heena West',
    dateOfService: '10-21-1995',
    noteType: 'SOAP',
    updatedDate: '10-21-1995',
    providerName: 'Jacob Jones',
    status: 'SIGNED',
    actionButton: [
      { label: 'Start', route: 'start' },
      { label: 'More', route: 'more' },
    ],
  },
  {
    appointmentType: 'Follow Up',
    profileIcon: 'https://i.pravatar.cc/150?img=4',
    patientName: 'Heena West',
    dateOfService: '10-21-1995',
    noteType: 'SOAP',
    updatedDate: '10-21-1995',
    providerName: 'Jacob Jones',
    status: 'UNSIGNED',
    actionButton: [
      { label: 'Start', route: 'start' },
      { label: 'More', route: 'more' },
    ],
  },
];

export const eprescriptionDialogData = {
  name: 'Henna West',
  dob: ' 10-07-1959 (65Yrs) (F)',
  mrn: ' 274747328',
  failureMessage:
    'This prescription did not reach the pharmacy due to communication issues, Contact Pillbox Pharmacy at (368) 34 7394',
  prescribedDrug: 'Acetaminophen 100mg/mL oral drop',
  date: 'Received Friday, March 04, 2023 08:30:54 PM',
  from: 'Clark Keller',
  to: 'Think EHR Team',
  instructions: 'Take one tablet once per day after a meal , do not take on empty stomach.',
  quantity: '100',
  dispenseFrom: 'John Torres',
  refill: '1',
  allowSubstitution: 'Yes',
  writtenOn: 'March 01, 2023',
  pharmacyNote: '-',
};

export const PROFILE_ROLES_SETTING_MOCK_DATA = [
  {
    description: 'Patients',
  },
  {
    description: 'Create Edit View Patient',
    uuid: 'create-edit-view-patient',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'View Patients',
    uuid: 'view-patients',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Share Patients',
    uuid: 'share-patients',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Appointments',
  },
  {
    description: 'Create Appointments',
    uuid: 'create-appointments',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'View Appointments',
    uuid: 'view-appointments',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Appointment Clinician Selection',
    uuid: 'appointment-clinician-selection',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Availability',
  },
  {
    description: 'Create Availability',
    uuid: 'create-availability',
    superAdmin: false,
    clinician: true,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'View Availability',
    uuid: 'view-availability',
    superAdmin: false,
    clinician: true,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Have Availability',
    uuid: 'have-availability',
    superAdmin: false,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
  {
    description: 'Documents - Intake',
  },
  {
    description: 'Edit Intake Documents',
    uuid: 'cat-documents-intake',
    superAdmin: true,
    clinician: false,
    staff: false,
    client: false,
    recordCustodian: false,
  },
];

export const APT_COLOR_CONFIGURATION_SETTING_MOCK_DATA = [
  {
    appointmentName: 'Confirmed',
    color: '#01C019',
    updatedDate: '20/05/2022',
    createdDate: '17/05/2022',
  },
  {
    appointmentName: 'Scheduled',
    color: '#4873B9',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Checked In',
    color: '#E59EFF',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Rescheduled',
    color: '#9688FF',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Cancelled',
    color: '#FF7E7E',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Pending Confirmation',
    color: '#FFD739',
    updatedDate: '20/05/2022',
    createdDate: '17/05/2022',
  },
  {
    appointmentName: 'No Show',
    color: '#8C8C8C',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Declined',
    color: '#7EDCFF',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
  {
    appointmentName: 'Signed Off',
    color: '#233853',
    updatedDate: '28/06/2022',
    createdDate: '10/05/2022',
  },
];
